version: '3'

volumes:
  node-modules-auto:
  node-modules-manual:


services:
  auto-app:
    build:
      context: "./"
      dockerfile: "DockerfileAuto"
    volumes:
      - ./services/sample-app/:/usr/local/src/
      - node-modules-auto:/usr/local/src/node_modules
    working_dir: /usr/local/src
    tty: true
    ports:
      - 3001:3000
  manual-app:
    build:
      context: "./"
      dockerfile: "DockerfileManual"
    volumes:
      - ./services/manual-app/:/usr/local/src/
      - node-modules-manual:/usr/local/src/node_modules
    working_dir: /usr/local/src
    tty: true
    ports:
      - 3002:3000
